### ISSUE TITLE
[Provider Audit] provider.www.akt-cryptobabou.com

### ISSUE THREAD

**Issue by CryptoBabou** [akash-network/community#463]
Hello !

Please can you pass the audit for provider.www.akt-cryptobabou.com ?

Discord handle : cryptobou

thank in advance,
CryptoBabou

**Comment by andy108369** [comment]
Hi @CryptoBabou !

It looks like your provider address isn't registered.
Are you sure it is online / working at all?

```
$ nslookup provider.www.akt-cryptobabou.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find provider.www.akt-cryptobabou.com: NXDOMAIN

```

**Comment by andy108369** [comment]
I've noticed you've opened https://github.com/akash-network/community/issues/464

is that the correct address there `provider.akth-cryptobabou.com` (i.e. not the `provider.www.akt-cryptobabou.com` in this ticket)?

**Comment by andy108369** [comment]
Closing as stale.
Please feel free to re-open it if needed.
