### ISSUE TITLE
[Provider Audit] provider.akashkansas.com

### ISSUE THREAD

**Issue by doverhimself** [akash-network/community#479]
### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name
2. Discord handle or Telegram handle
3. Contact email address

**Comment by andy108369** [comment]
Hi @doverhimself  and welcome to Akash Network!

I've checked your provider, it mostly looks good.
Except for the ingress ports aren't working.

They should forward the 80/tcp & 443/tcp traffic to your provider worker nodes and apparently it doesn't. Please see the screenshot:
![image](https://github.com/akash-network/community/assets/107317698/b5a21b88-c941-49c2-9773-e749f854cf45)


## Tests performed

- [x] provider bids (dseq 14905077)
- [x] nodePort OK
- [x] lease-shell/logs OK
- [ ] ingress Port - KO
- [x] speedtest OK (518 Mbit/s Up; 421 Mbit/s Down)
- [x] disk perf test OK

**Comment by doverhimself** [comment]
I'm running a single server rig via Praetor app. When I set it up it didn't
give me an ingress option. I'll see if that's in the settings for me to
change. Thanks!

**Comment by andy108369** [comment]
@doverhimself is your provider down?

I was about to check it now but found it is down:

```
$ ping provider.akashkansas.com
PING akashkc.ddns.net (104.60.165.60) 56(84) bytes of data.
^C
--- akashkc.ddns.net ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2050ms
```

```
$ nc -vz provider.akashkansas.com 8443
nc: connect to provider.akashkansas.com (104.60.165.60) port 8443 (tcp) failed: No route to host
```

**Comment by doverhimself** [comment]
Yes, I got two tiny leases, but they ended and I'm basically burning
electricity and AKT for nothing. I think I'll give the ecosystem a little
time to build out more demand and jump back in later. Thanks for checking
in, though!
