### ISSUE TITLE
[Provider Audit]: provider.akash-blkbox.cloud

### ISSUE THREAD

**Issue by freakinfofa** [akash-network/community#489]
### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name - Abraham
2. Discord handle or Telegram handle: freakin | blkbox
3. Contact email address: team@blkbox.cloud

**Comment by andy108369** [comment]
Hi @freakinfofa :wave: 

It looks like your provider isn't seeing my deployment order requests - dseq `15209027` & dseq `15209064`.
Please check if your RPC node is syncing with the tip of the chain.

Can you please pass me the output for these commands:

```
kubectl -n akash-services get pods

kubectl -n akash-services get pods -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[*].image'

kubectl -n akash-services exec -ti statefulset/akash-node-1 -- akash status

kubectl -n akash-services get statefulset/akash-provider -o yaml |grep -A1 AKASH_NODE

kubectl -n akash-services logs statefulset/akash-provider --tail=10000000 | grep -E '15209027|15209064'
```


Your provider is missing one attribute:
```
- key: host
  value: akash
```
![image](https://github.com/akash-network/community/assets/107317698/e100aa29-1197-4852-a3e4-274e472653e9)

Current attributes:

```
$ provider-services query provider get akash15yfjl6rz9u600ze48afspskg4mccx8fq5h6wp7 -o text 
attributes:
- key: organization
  value: blkbox.cloud
- key: tier
  value: community
- key: region
  value: us-east
- key: capabilities/storage/1/class
  value: beta3
- key: capabilities/cpu/arch
  value: x86-64
- key: capabilities/gpu/vendor/nvidia/model/1080ti
  value: "true"
- key: capabilities/cpu
  value: AMD
- key: capabilities/gpu
  value: nvidia
- key: network-speed-down
  value: "400"
- key: network-speed-up
  value: "100"
- key: capabilities/memory
  value: DDR4
- key: location-type
  value: home-office
- key: email
  value: team@blkbox.cloud
- key: status-page
  value: status.akash-blkbox.cloud
- key: capabilities/storage
  value: NVMe
host_uri: https://provider.akash-blkbox.cloud:8443
info:
  email: ""
  website: ""
owner: akash15yfjl6rz9u600ze48afspskg4mccx8fq5h6wp7
```

**Comment by freakinfofa** [comment]
kubectl -n akash-services get pods
NAME                                      READY   STATUS    RESTARTS       AGE
akash-hostname-operator-6795445db-nlq8r   1/1     Running   4 (14d ago)    51d
akash-provider-0                          1/1     Running   10 (23h ago)   8d

kubectl -n akash-services get pods -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[*].image'
NAME                                      IMAGE
akash-hostname-operator-6795445db-nlq8r   ghcr.io/akash-network/provider:0.4.8
akash-provider-0                          ghcr.io/akash-network/provider:0.4.8

kubectl -n akash-services exec -ti statefulset/akash-node-1 -- akash status
Error from server (NotFound): statefulsets.apps "akash-node-1" not found

kubectl -n akash-services get statefulset/akash-provider -o yaml |grep -A1 AKASH_NODE
        - name: AKASH_NODE
          value: http://99.209.150.74:26557
--
        - name: AKASH_NODE
          value: http://99.209.150.74:26557


kubectl -n akash-services logs statefulset/akash-provider --tail=10000000 | grep -E '15209027|15209064'
Defaulted container "provider" out of: provider, init (init)

**Comment by freakinfofa** [comment]
Im having some issues with the transfer.sh timing out... let me know if i can provide the logs via a different method?

curl -T provider.log.gz https://transfer.sh
curl: (28) Failed to connect to transfer.sh port 443 after 130359 ms: Connection timed out
