### ISSUE TITLE
[Provider Audit]: provider.aresakash.tech

### ISSUE THREAD

**Issue by doggyspacer** [akash-network/community#494]
### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host ingress.aresakash.tech (ip 46.173.164.46)
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name (Vladyslav)
2. Discord handle or Telegram handle (Dis Jolandemo#7347
3. Contact email address jolandemor@gmail.com

**Comment by andy108369** [comment]
Hi @doggyspacer  :wave: 

It looks like your provider isn't seeing my deployment order requests - dseq `15209169`.
Please check if your RPC node is syncing with the tip of the chain.

Can you please pass me the output for these commands:

```
kubectl -n akash-services get pods

kubectl -n akash-services get pods -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[*].image'

kubectl -n akash-services exec -ti statefulset/akash-node-1 -- akash status

kubectl -n akash-services get statefulset/akash-provider -o yaml |grep -A1 AKASH_NODE

kubectl -n akash-services logs statefulset/akash-provider --tail=10000000 | grep -E '15209169'
```

Please send me the provider logs too, this is done in two steps:

1. Create archive with your provider logs
```
kubectl -n akash-services logs statefulset/akash-provider --tail=10000000 | gzip -c > provider.log.gz
```
2. Upload that archive to transfer.sh using this CLI command:
```
curl -T provider.log.gz https://transfer.sh
```
The `curl -T ...` command will give you the output - the link where I can download your provider logs from. Please share this link with me here.



Current attributes:

```
$ provider-services query provider get akash1ejh0cjczhywcaw32dplngugvpgg63takurp3qj -o text 
attributes:
- key: organization
  value: arescc
- key: arch
  value: amd64
- key: host
  value: akash
- key: tier
  value: community
host_uri: https://provider.aresakash.tech:8443
info:
  email: ""
  website: ""
owner: akash1ejh0cjczhywcaw32dplngugvpgg63takurp3qj
```

**Comment by doggyspacer** [comment]
kubectl -n akash-services get pods
NAME                                      READY   STATUS    RESTARTS      AGE
akash-hostname-operator-6795445db-h8nb5   1/1     Running   7 (16h ago)   7d20h
akash-provider-0                          1/1     Running   0             70m

kubectl -n akash-services get pods -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[*].image'
NAME                                      IMAGE
akash-hostname-operator-6795445db-h8nb5   ghcr.io/akash-network/provider:0.4.8
akash-provider-0                          ghcr.io/akash-network/provider:0.4.8

kubectl -n akash-services exec -ti statefulset/akash-node-1 -- akash status
Error from server (NotFound): statefulsets.apps "akash-node-1" not found

kubectl -n akash-services get statefulset/akash-provider -o yaml |grep -A1 AKASH_NODE
        - name: AKASH_NODE
          value: http://99.209.150.74:26557
--
        - name: AKASH_NODE
          value: http://99.209.150.74:26557

kubectl -n akash-services logs statefulset/akash-provider --tail=10000000 | grep -E '15209169'
Defaulted container "provider" out of: provider, init (init)

https://transfer.sh/dkn9wbTou5/provider.log.gz

maybe it just coincided that at that moment +- there were several rentals at once

**Comment by andy108369** [comment]
Got the bid! dseq 15297464
Perhaps it just takes slightly longer time than usual for your provider to bid..
Might monitor your RPC node and I recommend you to deploy your own RPC node eventually.

I've tested & signed your provider.

tx hash `06A0A7AB790AED7EE6632CDA7B3296886DAAE6FC794DCC48867F74C8A56C7782`
