### ISSUE TITLE
[Provider Audit]: provider.akash-blkbox.cloud

### ISSUE THREAD

**Issue by freakinfofa** [akash-network/community#498]
### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)

Name - Abraham
Discord handle or Telegram handle: freakin | blkbox
Contact email address: [team@blkbox.cloud](mailto:team@blkbox.cloud)

**Comment by freakinfofa** [comment]
Hi! you can reference issue #489

Here is the outputs you requested:

kubectl -n akash-services get pods
NAME READY STATUS RESTARTS AGE
akash-hostname-operator-6795445db-nlq8r 1/1 Running 4 (14d ago) 51d
akash-provider-0 1/1 Running 10 (23h ago) 8d

kubectl -n akash-services get pods -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[*].image'
NAME IMAGE
akash-hostname-operator-6795445db-nlq8r ghcr.io/akash-network/provider:0.4.8
akash-provider-0 ghcr.io/akash-network/provider:0.4.8

kubectl -n akash-services exec -ti statefulset/akash-node-1 -- akash status
Error from server (NotFound): statefulsets.apps "akash-node-1" not found

kubectl -n akash-services get statefulset/akash-provider -o yaml |grep -A1 AKASH_NODE
- name: AKASH_NODE
value: http://99.209.150.74:26557
 - name: AKASH_NODE
 value: http://99.209.150.74:26557


kubectl -n akash-services logs statefulset/akash-provider --tail=10000000 | grep -E '15209027|15209064'
Defaulted container "provider" out of: provider, init (init)

**Comment by freakinfofa** [comment]
Having issues with the transfer.sh tool.. it just times out.

curl -T provider.log.gz https://transfer.sh
curl: (28) Failed to connect to transfer.sh port 443 after 130438 ms: Connection timed out

**Comment by freakinfofa** [comment]
let me know if I can provide the log file via a different method

**Comment by andy108369** [comment]
> let me know if I can provide the log file via a different method

@freakinfofa sure, you can email me the log file to andrey@akash.network

Make sure to specify the provider name in the subject. Thanks.

Also, your provider isn't responding over 8443 right now:
```
$ curl -k https://provider.akash-blkbox.cloud:8443/
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to provider.akash-blkbox.cloud:8443 
```

**Comment by freakinfofa** [comment]
Thanks! I will email them this evening when i get back home.

**Comment by andy108369** [comment]
It's been over 2 weeks.
Closing.

```
$ curl -k https://provider.akash-blkbox.cloud:8443/
curl: (7) Failed to connect to provider.akash-blkbox.cloud port 8443 after 201 ms: Couldn't connect to server
```

@freakinfofa  Please feel free to re-open the audit request whenever you are committed to run your provider.
