### ISSUE TITLE
[Provider Audit]: provider.tekti.net

### ISSUE THREAD

**Issue by matejkolin** [akash-network/community#520]
### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name
2. Discord handle or Telegram handle
3. Contact email address

Name: Matej
Discord: moljevski
Email: akash@tekti.net

**Comment by andy108369** [comment]
Hi @matejkolin :wave: 

I can't see the provider attributes on the chain:

```
$ provider-services query provider get akash1kjwufzvatm44f8ssqfvju2m5jcx7thlftewrrc -o json | jq -r .
{
  "owner": "akash1kjwufzvatm44f8ssqfvju2m5jcx7thlftewrrc",
  "host_uri": "https://provider.tekti.net:8443",
  "attributes": [
    {
      "key": "organization",
      "value": "Akash"
    },
    {
      "key": "arch",
      "value": "amd64"
    }
  ],
  "info": {
    "email": "",
    "website": ""
  }
}
```

Please review the "Attributes of Community Providers" section in https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors


We expect you to add these two provider attributes:
```
host: akash
tier: community
```

Also, we have updated the auditing docs and are now requiring adding these fields such as:
```
organization: <your org>
```

As well as two `informational` fields such as:
> can be done via your provider.yaml file
```
email: your@email.com
website: yourweb.com
```

You can refer to "Create a provider.yaml File" section in https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors document.

**Comment by matejkolin** [comment]
Hey, thank you for your prompt reply. I had those attributes filled out already but after restarting the provider they got deleted. Seems like an issue on the praetor side as I was told by Preator team.

```
akash@dev2:~$ provider-services query provider get akash1xxxxx
attributes:
- key: organization
  value: tekti
- key: arch
  value: amd64
- key: region
  value: eu-central
- key: host
  value: tekti.net
- key: tier
  value: community
- key: hardware-cpu
  value: intel
- key: hardware-cpu-arch
  value: x86-64
- key: hardware-disk
  value: hdd
- key: hardware-memory
  value: ddr4ecc
- key: network-provider
  value: TelekomSlovenije
- key: network-speed-up
  value: "40"
- key: network-speed-down
  value: "350"
host_uri: https://provider.tekti.net:8443
info:
  email: akash@tekti.net
  website: ""
owner: akash1kjwufzvatm44f8ssqfvju2m5jcx7thlftewrrc
```

**Comment by matejkolin** [comment]
Argh missed that one! Here you go:
```
akash@dev2:~$ provider-services query provider get akash1xxxx
attributes:
- key: organization
  value: tekti
- key: arch
  value: amd64
- key: region
  value: eu-central
- key: host
  value: akash
- key: tier
  value: community
- key: hardware-cpu
  value: intel
- key: hardware-cpu-arch
  value: x86-64
- key: hardware-disk
  value: hdd
- key: hardware-memory
  value: ddr4ecc
- key: network-provider
  value: TelekomSlovenije
- key: network-speed-up
  value: "40"
- key: network-speed-down
  value: "350"
host_uri: https://provider.tekti.net:8443
info:
  email: akash@tekti.net
  website: ""
owner: akash1xxx
```

**Comment by matejkolin** [comment]
Hey @andy108369, I just wanted to check in if there's something else I needed to do in order to get a positive audit?
Regards, Matej

**Comment by andy108369** [comment]
@matejkolin apologies for the delay.

I've tested your provider (with my deployment dseq `15800434) looks good:
- lease-shell :heavy_check_mark: 
- ingressPort :heavy_check_mark: 
- nodePort :heavy_check_mark: 


Your provider was signed!

https://www.mintscan.io/akash/tx/1A50A8698ABAB22A4DA82C11B071AA8D020E4AD6021EDE52DC16BF053C489907

**Comment by matejkolin** [comment]
@andy108369 Thank you!
