### ISSUE TITLE
[Provider Audit]: provider.jrgbuilding.net

### ISSUE THREAD

**Issue by spyder403** [akash-network/community#523]
### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name
2. Discord handle or Telegram handle
3. Contact email address

**Comment by andy108369** [comment]
Hi @spyder403 :wave: 
Your provider doesn't respond over 8443/tcp port.

Please correct this issue before I can start testing it:

``
$ curl -k https://provider.jrgbuilding.net:8443/status
<it just hangs here; it should display the provider stats instead>
```

And it should also be able to respond over 8444 (akash grpc) port:
```
$ grpcurl -insecure provider.jrgbuilding.net:8444 akash.provider.v1.ProviderRPC.GetStatus
<it just hangs here; it should display the provider stats instead>
```

**Comment by andy108369** [comment]
@spyder403  Your provider still not responding.
Closing this ticket due to inactivity.

Please feel free to reopen it anytime your provider is ready.

**Comment by spyder403** [comment]
do you guys have demand for 4090s i could bring them back? i only have now
unfortunately
