### ISSUE TITLE
[Provider Audit]: provider.arborcomputeservices.com

### ISSUE THREAD

**Issue by wardnath** [akash-network/community#526]
### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name
2. Discord handle or Telegram handle
3. Contact email address

**Comment by andy108369** [comment]
Hi @wardnath :wave: 

Your provider doesn't appear to be alive:
```
$ curl -k https://provider.arborcomputeservices.cloud:8443/status
curl: (6) Could not resolve host: provider.arborcomputeservices.cloud
```

**Comment by wardnath** [comment]
Hi @andy108369 🙌

Apologies, the title of the issue had a typo in my provider url. This command should work:

```bash
curl -k https://provider.arborcomputeservices.com:8443/status
```

**Comment by andy108369** [comment]
Hey @wardnath :wave: 

Your provider is missing certain attributes:

```
$ provider-services query provider get akash1t6xhw4c9yj9prjajk776733fdts072rm5lwwhr -o text
attributes:
- key: organization
  value: Arbor Compute Services Co
- key: arch
  value: amd64
host_uri: https://provider.arborcomputeservices.com:8443
info:
  email: ""
  website: ""
owner: akash1t6xhw4c9yj9prjajk776733fdts072rm5lwwhr
```

Please make sure your provider includes the standard attributes => https://akash.network/docs/providers/akash-audites-atributes/#standard-attributes  (those that are under `Attributes of Community Providers` in that doc as well as the `email` & `website` (if you have any) info fields - please do not mix them with the provider attributes)

**Comment by wardnath** [comment]
Hi @andy108369, my provider should be updated now.

```
$ provider-services query provider get akash1t6xhw4c9yj9prjajk776733fdts072rm5lwwhr -o text 
attributes:
- key: email
  value: arborcomputeservices@gmail.com
- key: host
  value: akash
- key: organization
  value: Arbor Compute Services Co
- key: location-region
  value: na-us-midwest
- key: capabilities/cpu
  value: intel
- key: capabilities/storage/3/class
  value: beta3
- key: capabilities/storage/2/class
  value: beta2
- key: capabilities/memory
  value: ddr4
- key: tier
  value: community
host_uri: https://provider.arborcomputeservices.com:8443
info:
  email: arborcomputeservices@gmail.com
  website: ""
owner: akash1t6xhw4c9yj9prjajk776733fdts072rm5lwwhr
```

**Comment by shimpa1** [comment]
hi @wardnath ,

If you have persistent storage, you also need to add the attribute:
`- key: feat-persistent-storage
  value: "true"`
Additionally, only one persistent storage class is supported per provider. It is either beta1 (HDD), beta2 (SSD) or beta3 (NVME), depending on your hardware.

Other aspects of your provider seem to be OK. Please add the above attribute if you do have persistent storage enabled or remove 
`- key: capabilities/storage/3/class
  value: beta3
- key: capabilities/storage/2/class
  value: beta2`
attributes because those pertain to persistent storage.
Once done and we have tested it, the provider should be good to go.

thank you!

**Comment by wardnath** [comment]
Hi @shimpa1 thank you. I actually don't have persistent storage enabled on my provider as of yet. I am planning on adding this capability but for now I just offer ephemeral storage. 

I've removed those attributes:

```
query provider get akash1t6xhw4c9yj9prjajk776733fdts072rm5lwwhr -o text
attributes:
- key: arch
  value: amd64
- key: host
  value: akash
- key: organization
  value: Arbor Compute Services Co
- key: location-region
  value: na-us-midwest
- key: capabilities/cpu
  value: intel
- key: capabilities/memory
  value: ddr4
- key: tier
  value: community
host_uri: https://provider.arborcomputeservices.com:8443
info:
  email: arborcomputeservices@gmail.com
  website: ""
owner: akash1t6xhw4c9yj9prjajk776733fdts072rm5lwwhr
```

**Comment by shimpa1** [comment]
@andy108369 Provider akash1t6xhw4c9yj9prjajk776733fdts072rm5lwwhr ready to be signed.

**Comment by wardnath** [comment]
Thank you @shimpa1 and @andy108369
