### ISSUE TITLE
[Provider Audit]: provider.us-west-1.acloud.zone

### ISSUE THREAD

**Issue by wynxV6Zywe** [akash-network/community#531]

**Comment by andy108369** [comment]
Hi @wynxV6Zywe , your provider doesn't appear to be alive:

```
$ curl -k https://provider.us-west-1.acloud.zone:8443/status
curl: (7) Failed to connect to provider.us-west-1.acloud.zone port 8443 after 174 ms: Couldn't connect to server
```

Please feel free to comment & re-open this request once it's back up again and it is ready to get signed.

Thank you.

To save time, please make sure it has the correct provider attributes & the info fields as described here https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors
