### ISSUE TITLE
[Provider Audit] provider.akash.cesspool.cc

### ISSUE THREAD

**Issue by sltmunky69** [akash-network/community#532]
### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name
2. Discord handle or Telegram handle
3. Contact email address

**Comment by andy108369** [comment]
Hi @sltmunky69 :wave: 

I've tested your provider is functioning well:
- ingressPorts :heavy_check_mark: 
- node Ports :heavy_check_mark: 
- internal networking :heavy_check_mark: 

Before I sign it with our auditing key, please add your contact details (email, website) as well:

```
$ provider-services query provider get akash1cvau0jl7s0dr75m6p6pye2aekwlucy99ms0xha -o text
attributes:
- key: organization
  value: Off The Chain Investments
- key: arch
  value: amd64
- key: host
  value: akash
- key: tier
  value: community
- key: region
  value: us-central
- key: cpu
  value: Intel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz
host_uri: https://provider.akash.cesspool.cc:8443
info:
  email: ""               <<<<<<<<<<<<<<< your contact email address
  website: ""           <<<<<<<<<<<<<<< your website if you have
owner: akash1cvau0jl7s0dr75m6p6pye2aekwlucy99ms0xha
```

Note that `info` fields are not the provider attributes.
They are separate fields.
In order to add them, simply add the following two lines to your `provider.yaml` file:
```
email: your@email.com
website: yourweb.com
```

Of course, set your `email` and `website`.

**Comment by sltmunky69** [comment]
Ok, should be all set there. Thank you!

**Comment by andy108369** [comment]
> Ok, should be all set there. Thank you!

Hey @sltmunky69 :wave: 
I've noticed you've set these as provider attributes, please read my above message carefully https://github.com/akash-network/community/issues/532#issuecomment-2044651195 -- these two (email & website) should go not as the provider attributes, but as the "info" fields.

```
$ provider-services query provider get akash1cvau0jl7s0dr75m6p6pye2aekwlucy99ms0xha -o text
attributes:
...
- key: email
  value: support@cesspool.cc
- key: website
  value: https://cesspool.cc
...
host_uri: https://provider.akash.cesspool.cc:8443
info:
  email: ""
  website: ""
owner: akash1cvau0jl7s0dr75m6p6pye2aekwlucy99ms0xha
```

**Comment by sltmunky69** [comment]
Ah, my apologies, I wasn't sure. I was pulling the information from the Provider Attributes Schema and didn't want to put an unsupported value in there and potentially break my node. It's there now.

**Comment by sltmunky69** [comment]
`$ provider-services query provider get akash1cvau0jl7s0dr75m6p6pye2aekwlucy99ms0xha -o text --node https://rpc.akash.forbole.com:443/
attributes:
- key: arch
  value: amd64
- key: host
  value: akash
- key: email
  value: support@cesspool.cc
- key: organization
  value: Off The Chain Investments
- key: website
  value: https://cesspool.cc
- key: location-region
  value: na-us-midwest
- key: location-type
  value: home
- key: country
  value: US
- key: timezone
  value: utc-6
- key: hardware-cpu
  value: intel
- key: hardware-cpu-arch
  value: x86-64
- key: hardware-disk
  value: ssd
- key: hardware-memory
  value: ddr3ecc
- key: network-provider
  value: i3 Broadband - Fiber
- key: network-speed-up
  value: "500"
- key: network-speed-down
  value: "500"
- key: feat-persistent-storage
  value: "false"
- key: capabilities/storage/2/class
  value: beta2
- key: capabilities/storage/2/persistent
  value: "false"
- key: capabilities/cpu
  value: intel
- key: capabilities/cpu/arch
  value: x86-64
- key: capabilities/memory
  value: ddr3ecc
- key: tier
  value: community
- key: ip-lease
  value: "false"
host_uri: https://provider.akash.cesspool.cc:8443
info:
  email: support@cesspool.cc
  website: https://cesspool.cc
owner: akash1cvau0jl7s0dr75m6p6pye2aekwlucy99ms0xha`

**Comment by andy108369** [comment]
Apologies for the delay.
Your provider has been signed!

tx hash: 790DC411CAADD9876509259CA97E52820D9B11351EAA9764711AA382781B92EB

**Comment by sltmunky69** [comment]
> Apologies for the delay. Your provider has been signed!
> 
> tx hash: 790DC411CAADD9876509259CA97E52820D9B11351EAA9764711AA382781B92EB

Two questions: 
Is there something I need to do with this hash, such as add it to provider.yaml?
If I add a GPU to my setup, do I need to reapply for an audit?
