### ISSUE TITLE
[Provider Audit] ttox.online

### ISSUE THREAD

**Issue by ttoX1** [akash-network/community#537]
1. Make sure your provider has community provider attributes and your contact details (email, website): DONE
2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP): Done
3. Please make sure your Akash provider doesn't block any Akash specific ports.: Done

Contact:
1. Scott Kania
2. ttoX1
3. scottkania@gmail.com

**Comment by andy108369** [comment]
Hey @ttoX1 :wave: 

You already had your provider audit request opened 2 weeks ago here https://github.com/akash-network/community/issues/533#issuecomment-2044659467

I've replied you there. Please take a look.

Closing this as duplicate.
