### ISSUE TITLE
[Provider Audit] : provider.oneworkspace.gr

### ISSUE THREAD

**Issue by ghostmasterftw** [akash-network/community#541]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: "<your email>"
    website: "<your website>"

```

[Ref documentation:](https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name
2. Discord handle or Telegram handle
3. Contact email address

**Comment by andy108369** [comment]
Hey @ghostmasterftw  :wave: 

Your provider is missing certain attributes:

```
$ provider-services query provider get akash1xmadcezvqdq4an3xtx7ta3pfzjndvy5fhhky0g -o text
attributes:
- key: organization
  value: VG
- key: arch
  value: amd64
host_uri: https://provider.oneworkspace.gr:8443
info:
  email: ""
  website: ""
owner: akash1xmadcezvqdq4an3xtx7ta3pfzjndvy5fhhky0g
```

Please make sure your provider includes the standard attributes => https://akash.network/docs/providers/akash-audites-atributes/#standard-attributes  (those that are under `Attributes of Community Providers` in that doc as well as the `email` & `website` (if you have any) info fields - please do not mix them with the provider attributes)

**Comment by ghostmasterftw** [comment]
hello  I already add the Email 

$ provider-services query provider get akash1xmadcezvqdq4an3xtx7ta3pfzjndvy5fhhky0g -o text
attributes:
- key: organization
  value: VG
- key: arch
  value: amd64
host_uri: https://provider.oneworkspace.gr:8443
info:
  email: vasileiosgalanis@gmail.com
  website: ""
owner: akash1xmadcezvqdq4an3xtx7ta3pfzjndvy5fhhky0g

**Comment by andy108369** [comment]
@ghostmasterftw mind reviewing a short section under https://akash.network/docs/providers/akash-audites-atributes/#standard-attributes ? :-)

**Comment by shimpa1** [comment]
@ghostmasterftw 
Your provider is missing the appropriate attributes. These are the current attributes:
`attributes:
- key: organization
  value: VG
- key: arch
  value: amd64
host_uri: https://provider.oneworkspace.gr:8443
info:
  email: ""
  website: ""
owner: akash1xmadcezvqdq4an3xtx7ta3pfzjndvy5fhhky0g`

Missing attributes:
- key: host
  value: akash
- key: organization
  value: <the name of your organization>
- key: tier
  value: community

The informational fields should also be populated with your email and website if you have it.

Please fix these attributes and we will begin testing the provider functionality.

thank you!

**Comment by ghostmasterftw** [comment]
i dont know where find the attributes there is no tab in akash preator
console  for complete the audit

Στις Τρί 7 Μαΐ 2024 στις 6:40 μ.μ., ο/η shimpa ***@***.***>
έγραψε:

**Comment by andy108369** [comment]
> i dont know where find the attributes there is no tab in akash preator console for complete the audit

@devalpatel67 @jigar-arc10  maybe you guys can provide some advise?

**Comment by devalpatel67** [comment]
You can add the missing attributes from the Praetor dashboard, like here - 
<img width="1714" alt="image" src="https://github.com/akash-network/community/assets/89543457/6ab3048c-331d-4b9f-bc1a-96b271135c5a">

**Comment by andy108369** [comment]
provider is offline and hasn't been responding for over two weeks.
@ghostmasterftw please feel free to re-open when ready.
