### ISSUE TITLE
[Provider Audit] provider.greendepin.cloud

### ISSUE THREAD

**Issue by dominikusbrian** [akash-network/community#555]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: "<your email>"
    website: "<your website>"

```

[Ref documentation:](https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Dominikus Brian
2. Discord: domizhong33
3. dev@dreambrook.tech

**Comment by shimpa1** [comment]
@dominikusbrian 

Please provide the following information:
- Your provider address (akash1.....)
- Your provider domain name

thank you!

**Comment by shimpa1** [comment]
@dominikusbrian 

Your provider is missing the appropriate attributes.
Current provider attributes:
provider-services query provider get akash1kz0t70zjeprtp9rsxwfwp85l7ccv6fcjpljgs3 -o text
attributes:
- key: organization
  value: greendepin
- key: arch
  value: amd64
host_uri: https://provider.greendepin.cloud:8443
info:
  email: ""
  website: ""
owner: akash1kz0t70zjeprtp9rsxwfwp85l7ccv6fcjpljgs3

Missing attributes:
- key: host
  value: akash
- key: tier
  value: community
Also please provide the contact information: the email address and the website if you have any.

thank you!
