### ISSUE TITLE
Proposal 242: Creating an automated auditor with open-source tooling + misc contributions to Cloudmos

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/community#569]
This is a project proposed by the PI3 team that passed on chain January 9th, 2024: https://www.mintscan.io/akash/proposals/242

**Comment by piber-dev** [comment]
Hello everyone. Yesterday we had a few topics we wanted to demo and present but unfortunately we had issues in planning. Here's a quick summary of the large topics we wanted to bring up in before our next meeting:

- Showcasing our indexer that automatically deploys different benchmarks to providers. It is fully written in Go and uses CLI commands in the background for all the wallet, blockchain, and deployment parts. It is not yet open-source.
- Demo the indexer and discuss what benchmarks and commands makes sense to run and save. Our idea is that while we can't process the data for all use-cases, we can easily index and archive outputs of commands for other people to process later on.
- Creating discussion a new trust system working alongside with KYC. Social media, wallet addresses, KYC or IRL attendance at events, and more information can potentially be used to verify users.
