### ISSUE TITLE
[Provider Audit]: provider.gpubase.xyz

### ISSUE THREAD

**Issue by twellener** [akash-network/community#573]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: "<your email>"
    website: "<your website>"

```

[Ref documentation:](https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Tyler Wellener
2. Discord: twell1
3. Contact email address: tyler@wellener.xyz

**Comment by shimpa1** [comment]
Hi @twellener,
Your provider has misconfigured attributes.
Current Attributes:

provider-services query provider get akash14f4jr40pvtvsa57u3arf3kexyrk87df5c72g3d -o text
attributes:
- key: organization
  value: GPU Base
- key: arch
  value: amd64
- key: capabilities/gpu/vendor/nvidia/model/4090
  value: "true"
- key: capabilities/gpu/vendor/nvidia/model/rtx4090/interface/pcie
  value: "true"
- key: capabilities/gpu/vendor/nvidia/model/rtx4090/ram/24Gi/interface/pcie
  value: "true"
- key: capabilities/gpu/vendor/nvidia/model/rtx4090
  value: "true"
- key: capabilities/gpu/vendor/nvidia/model/rtx4090/ram.24Gi
  value: "true"
- key: Discord
  value: twell1
- key: Website
  value: gpubase.xyz
host_uri: https://provider.gpubase.xyz:8443
info:
  email: ""
  website: ""
owner: akash14f4jr40pvtvsa57u3arf3kexyrk87df5c72g3d

- key: capabilities/gpu/vendor/nvidia/model/rtx4090/ram.24Gi
  value: "true"
  
This is a typo, the last dot should really be a /
Like this:

- key: capabilities/gpu/vendor/nvidia/model/rtx4090/ram/24Gi
  value: "true"

Second, the provider has missing attributes:
- key: tier
  value: community
- key: host
  value: akash
  
And third issue is that the provider is not responding on port 8444 / GRPC:
grpcurl -insecure provider.gpubase.xyz:8444 akash.provider.v1.ProviderRPC.GetStatus
Failed to dial target host "provider.gpubase.xyz:8444": context deadline exceeded

Please fix those issues and we can continue,

thank you!

**Comment by twellener** [comment]
Thanks @shimpa1. I've updated the misconfigured attributes. Please let me know if there's any other issues

**Comment by shimpa1** [comment]
@twellener 
The contact information should be in the info section. Having a key value pair for that is optional.
As soon as this is updated, the provider will be ready to be signed.

**Comment by twellener** [comment]
Just updated this on the following page: https://console.akash.network/providers/akash14f4jr40pvtvsa57u3arf3kexyrk87df5c72g3d?network=mainnet

Thanks for your help

**Comment by shimpa1** [comment]
@twellener 
there are now double attributes for website and email.
Please remove the ones in capital.

If your provider has persistent storage enabled then you also need this key:
- key: feat-persistent-storage
  value: true

If your provider does not have persistent storage enable then please remove attribute:
- key: capabilities/storage/2/class
  value: beta2

thank you,

**Comment by shimpa1** [comment]
Please do the following:
Log into the provider and edit the file ~/.praetor/provider.yaml
Add the lines:
email:           # set your email here
website:         # set your website (if you have)
Then do ```helm upgrade --install akash-provider akash/provider -n akash-services -f provider.yaml```
This should do the update, I've tested it.
Once done please let me know.
thank you,

**Comment by twellener** [comment]
Hey @shimpa1 - thanks again for your help on this. Just updated the file and upgraded!

**Comment by shimpa1** [comment]
@andy108369 Provider akash14f4jr40pvtvsa57u3arf3kexyrk87df5c72g3d ready to be signed.

**Comment by andy108369** [comment]
Signed!
https://www.mintscan.io/akash/txs/87732F97B3042B924B24D669F4D9CEEBD08CB414FBE41E88A9DE3D093B5ED1A2
