### ISSUE TITLE
[Provider Audit]:  provider.nodesaddicted.freeddns.org

### ISSUE THREAD

**Issue by NodesAddicted** [akash-network/community#584]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: "<your email>"
    website: "<your website>"

```

[Ref documentation:](https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name
2. Discord handle or Telegram handle
3. Contact email address

Diego
https://discord.com/channels/@nodesaddicted
https://t.me/nodesaddicted
contact@nodesaddicted.com

**Comment by shimpa1** [comment]
good morning @NodesAddicted ,
There's a few things that needs to be changed in the provider attributes:
This key is missing:
- key: host
  value: akash

This key needs to be specified as follows:
- key: tier
  value: community

These are optional but can remain:
- key: email
  value: contact@nodesaddicted.com
- key: website
  value: www.nodesaddicted.com  
however this information needs to go into the 

info:
  email: ""
  website: ""

section

Please update these and we can continue.

thank you!

**Comment by NodesAddicted** [comment]
Hi, can you check now ?

Thanks

**Comment by NodesAddicted** [comment]
Hi, can you check now ?

Thanks

**Comment by shimpa1** [comment]
Still the same.
```provider-services query provider get akash1q44w7qrqrh0lzwzjsyt0me6z646kdlgqf4gv2s -o text
attributes:
- key: email
  value: contact@nodesaddicted.com
- key: host
  value: akash
- key: organization
  value: NodesAddicted.com
- key: website
  value: www.nodesaddicted.com
- key: location-region
  value: undefined
- key: country
  value: IT
- key: city
  value: ROM
- key: timezone
  value: UTC+2
- key: location-type
  value: office
- key: capabilities/cpu
  value: undefined
- key: capabilities/cpu/arch
  value: undefined
- key: capabilities/storage/2/class
  value: beta2
- key: capabilities/memory
  value: undefined
- key: network-speed-up
  value: "150"
- key: network-speed-down
  value: "250"
- key: tier
  value: community
host_uri: https://provider.nodesaddicted.freeddns.org:8443
info:
  email: ""
  website: ""
owner: akash1q44w7qrqrh0lzwzjsyt0me6z646kdlgqf4gv2s```

Are you using Praetor or did you install using Helm?

**Comment by NodesAddicted** [comment]
I changed values using Praetor Provider Settings AND Akash Console (new) -> Provider details -> Edit

- key: host
  value: akash
- key: tier
  value: community

...as you asked me.

What is missing ?

**Comment by shimpa1** [comment]
Please do not use Akash Console to update the provider attributes.

The missing part is this:
```info:
  email: ""
  website: ""```

Also, since there is no persistent storage, this key is not required:
```- key: capabilities/storage/2/class
  value: beta2```

Please update the provider configuration manually.
Start an ssh session, edit the ~/.praetor/provider.yaml file and edit the info part manually.
Then update the provider using this command:
```helm upgrade --install akash-provider akash/provider -n akash-services -f provider.yaml ```

**Comment by NodesAddicted** [comment]
DONE

helm upgrade --install akash-provider akash/provider -n akash-services -f provider.yaml
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/diego/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/diego/.kube/config
Release "akash-provider" has been upgraded. Happy Helming!
NAME: akash-provider
LAST DEPLOYED: Tue Jun  4 16:19:13 2024
NAMESPACE: akash-services
STATUS: deployed
REVISION: 2
TEST SUITE: None

Should I remove this duplicated values?

    - key: email
      value: contact@nodesaddicted.com
    - key: website
      value: www.nodesaddicted.com

**Comment by shimpa1** [comment]
The attributes look good now.

Also tested making a deployment and it works.

One thing I would definitely suggest is to have more CPU available to the provider, right now it has only 4 VCPU allocated and only 1.2 VCPU available for deployments.

@andy108369 Provider akash1q44w7qrqrh0lzwzjsyt0me6z646kdlgqf4gv2s ready for signing.

**Comment by NodesAddicted** [comment]
yes, I know, I need a better computer...

THANKS for your support!

**Comment by NodesAddicted** [comment]
Hi, my node continue to be "NO AUDITED".

Can you support me ?

Thanks

**Comment by NodesAddicted** [comment]
> The attributes look good now.
> 
> Also tested making a deployment and it works.
> 
> One thing I would definitely suggest is to have more CPU available to the provider, right now it has only 4 VCPU allocated and only 1.2 VCPU available for deployments.
> 
> @andy108369 Provider akash1q44w7qrqrh0lzwzjsyt0me6z646kdlgqf4gv2s ready for signing.

Hi, my node continue to be "NO AUDITED".

Can you support me ?

Thanks

**Comment by andy108369** [comment]
Hi @NodesAddicted  :wave: 
I've just [signed](https://www.mintscan.io/akash/tx/58B53BDE13B2977BF0FBB0EE2D6FA9622E9B72E4021FEC284FDE710EFB4D82BE) your provider attributes.
Apologies for the delay.

**Comment by NodesAddicted** [comment]
THANKS for your support!
