### ISSUE TITLE
[Provider Audit] provider.rtx4090.xgcompute.com

### ISSUE THREAD

**Issue by silence48** [akash-network/community#597]
## Audit request for provider.rtx4090.xgcompute.com
contact-email: tim@xgcompute.com

provider details:
```
attributes:
- key: location-region
  value: na-us-southeast
- key: capabilities/storage/3/class
  value: beta3
- key: capabilities/memory
  value: ddr5
- key: capabilities/cpu
  value: intel
- key: capabilities/cpu/arch
  value: x86-64
- key: host
  value: akash
- key: tier
  value: community
- key: organization
  value: XG Compute
- key: network-speed-up
  value: "1000"
- key: network-speed-down
  value: "1000"
- key: timezone
  value: utc-6
- key: feat-persistent-storage
  value: "false"
- key: country
  value: US
- key: location-type
  value: datacenter
- key: capabilities/gpu
  value: nvidia
- key: capabilities/gpu/vendor/nvidia/model/rtx4090
  value: "true"
- key: capabilities/gpu/vendor/nvidia/model/rtx4090/ram/24Gi
  value: "true"
- key: capabilities/gpu/vendor/nvidia/model/rtx4090/ram/24Gi/interface/pcie
  value: "true"
- key: capabilities/gpu/vendor/nvidia/model/rtx4090/interface/pcie
  value: "true"
host_uri: https://provider.rtx4090.xgcompute.com:8443
info:
  email: tim@xgcompute.com
  website: xgcompute.com
owner: akash15dr2caktp8r2thxwj0kw9lj98t54fe3tp0e90g
```

**Comment by shimpa1** [comment]
hi Tim,
There seems to be an issue with the provider.
Our standard testing SDL does not work. After deploying that SDL, it completely stopped bidding and all functions that previously worked do not work anymore.
Please check the health of the provider, stability is the number one priority.
thank you,

**Comment by silence48** [comment]
> hi Tim, There seems to be an issue with the provider. Our standard testing SDL does not work. After deploying that SDL, it completely stopped bidding on any workload and all functions that previously worked do not work anymore. Please check the health of the provider, stability is the number one priority. thank you,

Hi shimpa, 

After working with your team on discord I believe we've identified any issues.  Appreciate the support!

**Comment by shimpa1** [comment]
@andy108369 
Provider akash15dr2caktp8r2thxwj0kw9lj98t54fe3tp0e90g ready to be signed
