### ISSUE TITLE
[Provider Audit]: provider.armada21.com

### ISSUE THREAD

**Issue by JesseGeo** [akash-network/community#612]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: "<your email>"
    website: "<your website>"

```

[Ref documentation:](https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Armada
2. Discord:  armada.nodes
3. Email:  armada_admin@protonmail.com

**Comment by JesseGeo** [comment]
I have 2 GPUs, an A6000 and a 3090.  I hope that I have configured my provider properly so that both of these GPUs are available for tenants.  In my attributes I have:

capabilities/gpu						          nvidia
capabilities/gpu/vendor/nvidia/model/rtxA6000         true
capabilities/gpu/vendor/nvidia/model/rtx3090		   true

**Comment by shimpa1** [comment]
hi @JesseGeo ,
A few things:
In your provider.yaml there is an info section
```info:
  email: ""
  website: ""```
  Please fill these values in and update the provider.
 
 Another thing is you have a single node but 2 different GPUs. A provider can have multiple GPU types on offer however only a single type per worker node.
 
Please correct these and we can continue.

Thank you!

**Comment by JesseGeo** [comment]
Actually there wasn't an info section, but I've added one.  Can you check the screen capture please?  I have email and website in my attributes, should they be removed from attributes, then?
![provider_yaml](https://github.com/akash-network/community/assets/37090029/57a32868-62a0-4b03-8a1d-21d52dfde9f8)

**Comment by shimpa1** [comment]
Just append to the bottom of provider.yaml

email: armada_admin@protonmail.com
website: armada21.info

**Comment by JesseGeo** [comment]
I made the edit to provider.yaml and I hit the restart button in the Praetor provider settings page.  The provider seems to be up and running, although now it is not showing up in Cloudmos provider list.

**Comment by shimpa1** [comment]
The provider is not responding on any of the status endpoints and it is not placing bids.
Please check that the provider pod is running:
```kubectl -n akash-services get pods```

**Comment by JesseGeo** [comment]
Yup, looks like it's running.  I've attached a screen capture.
![Captura desde 2024-06-27 15-15-22](https://github.com/akash-network/community/assets/37090029/e7c6e791-36a4-47e1-917e-7b5a32e9abe3)

**Comment by JesseGeo** [comment]
Can we continue with the audit?

**Comment by shimpa1** [comment]
good morning,
The team is at EthCC so the reaction times are slower than usual.
Your provider seems to be unavailable a lot. It needs to be stable in order to get signed.
![Screenshot 2024-07-08 074000](https://github.com/akash-network/community/assets/20532068/e09999db-03cd-4479-8825-f28f82ef7082)

**Comment by andy108369** [comment]
Hi @JesseGeo :wave: 
Your provider seem to be offline, i.e. it is not responding over 8443/tcp port at `provider.armada21.com` address.

```
$ curl -k https://provider.armada21.com:8443/status
<hangs here>
```
