### ISSUE TITLE
[Provider Audit]: provider.digilob.net

### ISSUE THREAD

**Issue by digilob1** [akash-network/community#639]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: info@digilob.net

```

[Ref documentation:](https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name - digilob
2. Discord handle - digitallobster
3. Contact email address - info@digilob.net

**Comment by shimpa1** [comment]
hi @digilob1 ,
There's a few provider attributes missing:

provider-services query provider get akash1fhe99jw8yz35pr9z7g7cn6tnea3hyxzxmf84sa -o text
attributes:
- key: organization
  value: digilob
- key: arch
  value: amd64
- key: host
  value: akash
- key: tier
  value: community
- key: email
  value: info@digilob.net
host_uri: https://provider.digilob.net:8443
info:
  email: ""
  website: ""
owner: akash1fhe99jw8yz35pr9z7g7cn6tnea3hyxzxmf84sa

The info: section needs to be pupulated.
If you have installed the provider using Praetor, please 
- log into your primary control node 
- edit the file ~/praetor/provider.yaml
- add the missing attributes
- helm upgrade --install akash-provider akash/provider -n akash-services -f `/praetor/provider.yaml --set bidpricescript="$(cat ~/provider/price_script_generic.sh | openssl base64 -A)"

If you have installed using standard Akash Helm charts installation, please 
- log into your primary control node 
- edit the file ~/provider/provider.yaml
- add the missing attributes
- helm upgrade --install akash-provider akash/provider -n akash-services -f ~/provider/provider.yaml --set bidpricescript="$(cat ~/provider/price_script_generic.sh | openssl base64 -A)"

We can continue after that is completed

thank you,

**Comment by digilob1** [comment]
@shimpa1 I've updated the provider.yaml file.

**Comment by andy108369** [comment]
> @shimpa1 I've updated the provider.yaml file.

@digilob1 the `info` sections is still empty:

```
$ provider-services query provider get akash1fhe99jw8yz35pr9z7g7cn6tnea3hyxzxmf84sa -o text
attributes:
- key: organization
  value: digilob
- key: arch
  value: amd64
- key: host
  value: akash
- key: tier
  value: community
- key: email
  value: info@digilob.net
host_uri: https://provider.digilob.net:8443
info:
  email: ""
  website: ""
owner: akash1fhe99jw8yz35pr9z7g7cn6tnea3hyxzxmf84sa
```

And `email` shouldn't be a part of the provider attribute, but the `info` field.

Please refer to `Attributes of Community Providers` section in https://akash.network/docs/providers/audited-attributes/

In your case you basically only need to remove the `email` provider attribute and add `email: info@digilob.net` without the indentation (i.e. without the empty spaces before that line), and then apply the changes (the provider helm chart update)

**Comment by andy108369** [comment]
Closing this as the provider is no longer active and the owner has not been responsive.
