### ISSUE TITLE
[Provider Audit] provider.bigtractorcompute.com

### ISSUE THREAD

**Issue by jmhands** [akash-network/community#642]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: "<your email>"
    website: "<your website>"

```

[Ref documentation:](https://akash.network/docs/providers/akash-audites-atributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name: JM Hands
2. Discord handle or Telegram handle: @jmhands
3. Contact email address: jm@farmgpu.com

**Comment by shimpa1** [comment]
hi JM, welcome back,

These are your current attributes:

provider-services query provider get akash1kkjkd0pv0c7r53luacjj6aeaaalerjjnh7z9kv -o text
attributes:
- key: region
  value: us-west
- key: chia-plotting
  value: ""
- key: host
  value: akash
- key: cpu
  value: Intel
- key: tier
  value: ""
- key: network_download
  value: "10000"
- key: network_upload
  value: "10000"
- key: status
  value: https://status.bigtractorcompute.com
- key: capabilities/storage/1/class
  value: beta1
- key: capabilities/storage/1/persistent
  value: "true"
- key: capabilities/storage/2/class
  value: beta2
- key: capabilities/storage/2/persistent
  value: "true"
- key: capabilities/storage/3/class
  value: beta3
- key: capabilities/storage/3/persistent
  value: "true"
host_uri: https://provider.bigtractorcompute.com:8443
info:
  email: jm@farmgpu.com
  website: farmgpu.com
owner: akash1kkjkd0pv0c7r53luacjj6aeaaalerjjnh7z9kv

There's a few missing attributes:

The "tier" value should be set to "community"

- key: tier
  value: community

The "organization" key is missing;
- key: organization
  value: 

I presume you will want to do Chia plotting, please use:

- key: chia-plotting
  value: true
- key: workload-support-chia
  value: true

The persistent storage should be set to beta3 (you are using nvme drives I presume). The other keys should be deleted. 
- key: capabilities/storage/1/class
  value: beta1
- key: capabilities/storage/1/persistent
  value: "true"
- key: capabilities/storage/2/class
  value: beta2
- key: capabilities/storage/2/persistent
  value: "true"
  
In case your provider does not have persistent storage, all keys pertaining to it should be removed.

Next, upon trying to deploy a beta3 workload (a wordpress site) your provider did not place a bid.
The inventory operator does not seem to be aware of any persistent storage. Please go through the steps explained here:
https://akash.network/docs/providers/build-a-cloud-provider/helm-based-provider-persistent-storage-enablement/
Please feel free to skip those steps in case you do not plan on having persistent storage enabled.

thanks,

Shimpa

**Comment by jmhands** [comment]
awesome, hit me up again to catch up sir!!

I'm adding 12 more nodes next week with NVMe, should I just leave beta3 on and set the others to false?

        --set attributes[8].key=capabilities/storage/1/class --set attributes[8].value=beta1 \
        --set attributes[9].key=capabilities/storage/1/persistent --set attributes[9].value=true \
        --set attributes[10].key=capabilities/storage/2/class --set attributes[10].value=beta2 \
        --set attributes[11].key=capabilities/storage/2/persistent --set attributes[11].value=true \
        --set attributes[12].key=capabilities/storage/3/class --set attributes[12].value=beta3 \
        --set attributes[13].key=capabilities/storage/3/persistent --set attributes[13].value=true \

**Comment by shimpa1** [comment]
Sounds good!
Just delete the others referencing either beta1 or beta2.
I can help you on Discord, might be faster.

**Comment by jmhands** [comment]
all right I just turned off for now, should be ready to verify. I will get more comfortable with the ceph / rook before I add back in. Please add me again on Discord! you have DMs off 😉

**Comment by shimpa1** [comment]
@andy108369 Provider akash1kkjkd0pv0c7r53luacjj6aeaaalerjjnh7z9kv ready to be signed

**Comment by andy108369** [comment]
> @andy108369 Provider akash1kkjkd0pv0c7r53luacjj6aeaaalerjjnh7z9kv ready to be signed

[Signed](https://www.mintscan.io/akash/tx/F9B83626A0FBF9CA797F4EE743D34E67F61AC0D518B4BBC65F1320569EEC974D).
Apologies for the delay.

**Comment by andy108369** [comment]
@jmhands I suggest you topping up the provider balance a bit more than it currently has ~0.49 AKT
