### ISSUE TITLE
[Provider Audit]: akash01.agwswebconsulting.it

### ISSUE THREAD

**Issue by v1per4llbl4ck** [akash-network/community#686]
1. Alberto Galassi
2. Discord handle or Telegram handle:  v1per4llbl4ck  telegram: @v1p3r4llbl4ck
3. agalassi@agwswebconsulting.it

**Comment by v1per4llbl4ck** [comment]
Cluster Name
provider.akash01.agwswebconsulting.it

**Comment by shimpa1** [comment]
- provider address: akash1xecxcjulexrlyal3vepk5l8fa7g5syukkn86qm
- provider URI name resolution works: yes
- provider ingress URI name resolution works: yes
- provider status endpoint works: yes
- provider GRPC status endpoint works: yes
- provider attributes set correctly: NO
- provider responding to orders: NO
- test deployment works: N/A
- network functional: N/A

The provider is not answering to orders. Please make sure the provider is fully functional.

Other remarks: The provider attributes are not set correctly. Mandatory fields are:
- key: region
  value: <region>
- key: host
  value: akash
- key: tier
  value: community
  - key: organization
  value: <organization name>

Besides those fields, the info: section needs to be populated:
info:
  email: ""
  website: ""
  
Please fix all these issues and we will continue.

thank you,

Shimpa

**Comment by v1per4llbl4ck** [comment]
![image](https://github.com/user-attachments/assets/7bab4f71-d694-4767-ab8e-ac4db6ab638b)

on discord Bhavik | Praetor App test me one order and it was right and submitted.

so is functional.

email
agalassi@agwswebconsulting.it
website
www.agwswebconsulting.it

thanks for support

**Comment by v1per4llbl4ck** [comment]
i had remove the info from attribute and inserted in provider.yml

**Comment by v1per4llbl4ck** [comment]
its possible speed up the audit i need more visibility because i miss more akt in 3 days 
13.74199
13.73698
13.70674
13.66202
13.59178
13.55516 
13.53499
13.53499
13.51850
13.51363
13.50866
13.43697

**Comment by shimpa1** [comment]
hi,

provider-services query provider get akash1xecxcjulexrlyal3vepk5l8fa7g5syukkn86qm -o text
attributes:
- key: organization
  value: Agws
- key: arch
  value: amd64
- key: cores
  value: "6"
- key: ram
  value: 22GB
- key: disk
  value: 500GB
- key: region
  value: DE
- key: host
  value: akash
- key: tier
  value: community
host_uri: https://provider.akash01.agwswebconsulting.it:8443
info:
  email: ""
  website: ""
owner: akash1xecxcjulexrlyal3vepk5l8fa7g5syukkn86qm

The info: section needs to be populated. Please add it to your provider.yaml file and update the provider with 

helm upgrade --install akash-provider akash/provider -n akash-services -f provider.yaml --set bidpricescript="$(cat ~/provider/price_script_generic.sh | openssl base64 -A)"

Furher, the provider is not responding to status endpoint:
curl -k https://provider.akash01.agwswebconsulting.it:8443/status | jq

curl: (7) Failed to connect to provider.akash01.agwswebconsulting.it port 8443 after 35 ms: Connection refused

Please make sure everything works before requesting an audit, thank you

**Comment by andy108369** [comment]
provider is still offline:
```
$ nc -vz provider.akash01.agwswebconsulting.it 8443
nc: connect to provider.akash01.agwswebconsulting.it (62.169.31.147) port 8443 (tcp) failed: Connection refused
```

@v1per4llbl4ck any updates?
