### ISSUE TITLE
[Provider Audit] provider.akash.colnetwork.com

### ISSUE THREAD

**Issue by jars101** [akash-network/community#711]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):
Done

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
root@akash-1:/home/user# host aaa.ingress.akash.colnetwork.com
aaa.ingress.akash.colnetwork.com is an alias for akash.colnetwork.com.
akash.colnetwork.com has address 161.10.254.22

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
Confirmed

  
## Leave contact information (optional)
1. Name: Jairo Rizzo
2. Discord handle or Telegram handle: Colnet in Discord
3. Contact email address: soporte@colnetwork.com

**Comment by shimpa1** [comment]
hi @jars101 ,
Provider name: provider.akash.colnetwork.com
Provider address: akash1hqnu7hg59jg4579p65s5zmukgqss6ev28yg0sg
Provider URI name resolution works?: YES
Provider Ingress name resolution works?: YES
Provider responding to orders?: NO
Deployment works?: NO
Network functional?: N/A
attributes OK?: NO
status endpoint works?: YES
GRPC status endpoint works?: YES

First provider attributes:
provider-services query provider get akash1hqnu7hg59jg4579p65s5zmukgqss6ev28yg0sg -o text
attributes:
- key: organization
  value: colnetwork
- key: arch
  value: amd64
- key: tier
  value: community
- key: email
  value: soporte@colnetwork.com
- key: website
  value: colnetwork.com
- key: region
  value: sa-west-1
- key: capabilities/cpu
  value: intel
- key: network-speed-up
  value: "1000"
- key: network-speed-down
  value: "1000"
- key: capabilities/storage/2/class
  value: beta3
host_uri: https://provider.akash.colnetwork.com:8443
info:
  email: ""
  website: ""
owner: akash1hqnu7hg59jg4579p65s5zmukgqss6ev28yg0sg

This key-value pair:
- key: capabilities/storage/2/class
  value: beta3
  
Pertains to persistent storage which your provider doesn't have. Please remove it.

The info section needs to be populated as well.

Also, your provider is not responding to orders. 

Please fix those issues then we can continue.

thanks,
Shimpa

**Comment by jars101** [comment]
Unfortunately, I have tried like 20 times to get orders to work but im still unable to do so. Discord channel not being very helpful.  I have read the majority of the docs at https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/ and https://akashengineers.xyz/provider-build-scripts/  multiple times.

**Comment by jars101** [comment]
I honestly dont want to give up also when i have bough like 100 AKT already tryhing to set this up.

**Comment by shimpa1** [comment]
Of course not.
Contact me on Discord Directly.

**Comment by shimpa1** [comment]
Update:

Provider name: provider.akash.colnetwork.com
Provider address: akash1hqnu7hg59jg4579p65s5zmukgqss6ev28yg0sg
Provider URI name resolution works?: YES
Provider Ingress name resolution works?: YES
Provider responding to orders?: YES
Deployment works?: YES
Network functional?: YES
attributes OK?: YES
status endpoint works?: YES
GRPC status endpoint works?: YES

@andy108369 
Provider akash1hqnu7hg59jg4579p65s5zmukgqss6ev28yg0sg ready to be signed

**Comment by jars101** [comment]
Hello, so I redeployed my cluster from scratch and added 2 gpu worker nodes. One with a t4 and one with a rtx 3050 (this one is not yet listed by you so I opened https://github.com/akash-network/provider-configs/issues/37 ) . Please advice if all ok . This is the final production cluster deployment with 3 control plane nodes + multiple workers.

**Comment by jars101** [comment]
Hello again, kindly please provide an update. Thanks

**Comment by jars101** [comment]
Hello, added persistent storage.

**Comment by jars101** [comment]
Hello again, kindly please provide an update. Thanks

**Comment by jars101** [comment]
Hello again, kindly please provide an update. Thanks

**Comment by shimpa1** [comment]
Provider revisited today - it is offline.

**Comment by andy108369** [comment]
Please open a new request once your provider is stable enough.
Thanks.

**Comment by jars101** [comment]
@andy108369 @shimpa1 I've been highlighting the lack of support on the Discord channel, to the point of getting blocked. I've been waiting for an audit to review storage persistence and resolve issues with nginx (k3s) - [https://github.com/nginx/nginx/issues/226#issuecomment-2462209719 ](https://github.com/nginx/nginx/issues/226#issuecomment-2462209719)and [https://github.com/chainzero/provider-build-scripts/issues/20 ](https://github.com/chainzero/provider-build-scripts/issues/20). Additionally, I reported a critical error with NVIDIA GPU worker node that still remains unanswered:

`[Thu Dec  5 10:02:01 2024] WARNING: kernel stack frame pointer at 00000000ba47703c in akash:9329 has bad value 00000000f55ca2b7
[Thu Dec  5 10:02:01 2024] unwind stack type:0 next_sp:0000000000000000 mask:0x2 graph_idx:0
[Thu Dec  5 10:02:01 2024] 000000004576e520: ffffa95daf083b70 (0xffffa95daf083b70)
[Thu Dec  5 10:02:01 2024] 00000000a3c50e5b: ffffffffc114b98a (os_release_spinlock+0x1a/0x30 [nvidia])
[Thu Dec  5 10:02:01 2024] 00000000ba47703c: ffff8a860547aed0 (0xffff8a860547aed0)
[Thu Dec  5 10:02:01 2024] 00000000b3f6145a: ffffffffc116c362 (_nv014133rm+0x4e2/0xb90 [nvidia])
`
Despite reaching out, I'm not seeing any progress. As a provider, this is not only frustrating but also causing me financial losses. Notably, my experience with Filecoin has been seamless, with responsive support and profit. It's concerning to see such a disparity in support between networks. Can I reasonably expect support from the Akash Network?

**Comment by jars101** [comment]
Now you're asking me to open a new audit request?
