### ISSUE TITLE
[Provider Audit]  provider.4090.akashgpu.com

### ISSUE THREAD

**Issue by Zblocker64** [akash-network/community#749]
Please Audit. Thanks
  

Discord = Zblocker64

**Comment by shimpa1** [comment]
hi @Zblocker64 ,
This is the status of the audit process:
Provider name: provider.4090.akashgpu.com
Provider address: akash1ut3m97h62tty06qdq9lds85r34dxe3snjj0xfe
Provider URI: provider.4090.akashgpu.com
Provider URI name resolution works? yes
Ingress URI name resolution works? yes
Provider status endpoint works? yes
Provider grpc status endpoint works? yes
Provider responding to orders? yes
Deployment works? in progress
SSH works? in progress
Network functional? in progress
Attributes OK? NO
Other remarks: provider is missing [custom kernel parameters](https://akash.network/docs/providers/build-a-cloud-provider/kubernetes-cluster-for-akash-providers/kubernetes-cluster-for-akash-providers/#create-and-apply-custom-kernel-parameters) which allow the creation of larger amount of files.

This is an excerpt from the provider attributes which is missing:
host_uri: https://provider.4090.akashgpu.com:8443
info:
  email: ""
  website: ""

Please add this information via your provider.yaml file and apply it.

Once the custom kernel parameters are set up and the attributes are set please let us know.

**Comment by Zblocker64** [comment]
Done @shimpa1 Thanks!

**Comment by shimpa1** [comment]
signed

"height":"19226332","txhash":"E5B679B14C2B95D9FAEEF7C33AF85F40C72214F6CA3E31358E0381AD0E0579D3"
