### ISSUE TITLE
chore: sig-provider detailed meeting notes update for 02-2023-02-22.md

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/community#94]
@figurestudios will add detail notes for sig provider meeting 2: https://github.com/akash-network/community/blob/main/sig-providers/meetings/002-2023-02-22.md

**Comment by figurestudios** [comment]
https://github.com/akash-network/community/pull/97

**Comment by figurestudios** [comment]
Issue can be closed now @brewsterdrinkwater
